import type { SensitivityEntry } from "@/types/schema";
import { supabase } from "@/utils/supabase";

import { requireUser } from "./auth";
import { getDatabase } from "./database";
import { dequeueSync, enqueueSync } from "./sync-queue";

function now() {
  return new Date().toISOString();
}

function swallow(p: PromiseLike<unknown>) {
  Promise.resolve(p).catch(() => {});
}

// Local sqlite autoincrement ids are NOT server ids (the server uses
// `bigint generated by default as identity`), so rows are matched across
// devices by natural key. Timestamps are compared by epoch millis because
// the server may reformat the ISO string.
type NaturalKey = { user_id: string; trigger_cause: string; occurred_at: string };

function naturalKeyEquals(a: NaturalKey, b: NaturalKey): boolean {
  return (
    a.user_id === b.user_id &&
    a.trigger_cause === b.trigger_cause &&
    new Date(a.occurred_at).getTime() === new Date(b.occurred_at).getTime()
  );
}

async function findLocalIdByNaturalKey(
  db: Awaited<ReturnType<typeof getDatabase>>,
  key: NaturalKey,
): Promise<number | null> {
  const rows = await db.getAllAsync<{ id: number; occurred_at: string }>(
    `SELECT id, occurred_at FROM sensitivity_history WHERE user_id = ? AND trigger_cause = ?`,
    [key.user_id, key.trigger_cause],
  );
  const target = new Date(key.occurred_at).getTime();
  for (const row of rows) {
    if (new Date(row.occurred_at).getTime() === target) return row.id;
  }
  return null;
}

async function mergeServerRow(
  db: Awaited<ReturnType<typeof getDatabase>>,
  row: {
    user_id: string;
    trigger_cause: string;
    severity: string;
    notes: string | null;
    occurred_at: string;
    created_at: string;
  },
): Promise<void> {
  const existingId = await findLocalIdByNaturalKey(db, row);
  if (existingId !== null) {
    // Same entry already exists locally (possibly with a different local
    // id) — update it in place instead of inserting a duplicate.
    await db.runAsync(
      `UPDATE sensitivity_history
       SET trigger_cause = ?, severity = ?, notes = ?, occurred_at = ?, created_at = ?, synced_at = ?
       WHERE id = ?`,
      [
        row.trigger_cause,
        row.severity,
        row.notes ?? null,
        row.occurred_at,
        row.created_at,
        now(),
        existingId,
      ],
    );
  } else {
    await db.runAsync(
      `INSERT INTO sensitivity_history
       (user_id, trigger_cause, severity, notes, occurred_at, created_at, synced_at)
       VALUES (?, ?, ?, ?, ?, ?, ?)`,
      [
        row.user_id,
        row.trigger_cause,
        row.severity,
        row.notes ?? null,
        row.occurred_at,
        row.created_at,
        now(),
      ],
    );
  }
}

export async function getSensitivityHistory(): Promise<SensitivityEntry[]> {
  const user = await requireUser();
  const db = await getDatabase();

  const local = await db.getAllAsync<{
    id: number;
    trigger_cause: string;
    severity: string;
    notes: string | null;
    occurred_at: string;
    created_at: string;
  }>(
    `SELECT id, trigger_cause, severity, notes, occurred_at, created_at
     FROM sensitivity_history WHERE user_id = ?
     ORDER BY occurred_at DESC, id DESC`,
    [user.id],
  );

  if (local.length > 0) {
    // Refresh in background if online, without resurrecting locally deleted rows
    swallow(
      (async () => {
        const { data } = await supabase
          .from("sensitivity_history")
          .select("*")
          .eq("user_id", user.id);
        if (!data?.length) return;

        const queue = await dequeueSync();
        const pendingDeletes = queue.filter(
          (e) =>
            e.table_name === "sensitivity_history" &&
            e.operation === "delete",
        );

        for (const row of data) {
          const deleted = pendingDeletes.some((e) =>
            naturalKeyEquals(e.payload as NaturalKey, {
              user_id: row.user_id,
              trigger_cause: row.trigger_cause,
              occurred_at: row.occurred_at,
            }),
          );
          if (deleted) continue;
          await mergeServerRow(db, {
            user_id: row.user_id,
            trigger_cause: row.trigger_cause,
            severity: row.severity,
            notes: row.notes ?? null,
            occurred_at: row.occurred_at,
            created_at: row.created_at,
          });
        }
      })(),
    );
    return local;
  }

  try {
    const { data, error } = await supabase
      .from("sensitivity_history")
      .select("*")
      .eq("user_id", user.id)
      .order("occurred_at", { ascending: false });
    if (error) throw error;

    for (const row of data) {
      await mergeServerRow(db, {
        user_id: user.id,
        trigger_cause: row.trigger_cause,
        severity: row.severity,
        notes: row.notes ?? null,
        occurred_at: row.occurred_at,
        created_at: row.created_at,
      });
    }
    return data.map((row) => ({
      id: row.id,
      trigger_cause: row.trigger_cause,
      severity: row.severity,
      notes: row.notes ?? null,
      occurred_at: row.occurred_at,
      created_at: row.created_at,
    }));
  } catch {
    return [];
  }
}

export async function addSensitivityEntry(input: {
  trigger_cause: string;
  severity: string;
  notes?: string;
}): Promise<void> {
  const user = await requireUser();
  const db = await getDatabase();
  const ts = now();

  const result = await db.runAsync(
    `INSERT INTO sensitivity_history (user_id, trigger_cause, severity, notes, occurred_at, created_at, synced_at)
     VALUES (?, ?, ?, ?, ?, ?, ?)`,
    [
      user.id,
      input.trigger_cause,
      input.severity,
      input.notes?.trim() || null,
      ts,
      ts,
      ts,
    ],
  );

  // The local autoincrement id is never sent to the server — the server
  // generates its own bigint id. Entries are matched by natural key on sync.
  const serverPayload = {
    user_id: user.id,
    trigger_cause: input.trigger_cause,
    severity: input.severity,
    notes: input.notes?.trim() || null,
    occurred_at: ts,
    created_at: ts,
  };

  await enqueueSync(
    "sensitivity_history",
    "upsert",
    String(result.lastInsertRowId),
    serverPayload,
  );

  try {
    const { error } = await supabase
      .from("sensitivity_history")
      .insert(serverPayload);
    if (error) throw error;
  } catch {
    // Will be retried on next connectivity change
  }
}

export async function deleteSensitivityEntry(id: number): Promise<void> {
  const user = await requireUser();
  const db = await getDatabase();

  // Read the row first: the sync queue needs the natural key because the
  // local id is meaningless to the server.
  const row = await db.getFirstAsync<{
    trigger_cause: string;
    occurred_at: string;
  }>(
    `SELECT trigger_cause, occurred_at FROM sensitivity_history WHERE id = ? AND user_id = ?`,
    [id, user.id],
  );
  if (!row) return;

  await db.runAsync(`DELETE FROM sensitivity_history WHERE id = ? AND user_id = ?`, [
    id,
    user.id,
  ]);

  const deletePayload = {
    user_id: user.id,
    trigger_cause: row.trigger_cause,
    occurred_at: row.occurred_at,
  };
  await enqueueSync("sensitivity_history", "delete", String(id), deletePayload);

  try {
    const { data: matches, error: lookupError } = await supabase
      .from("sensitivity_history")
      .select("id")
      .eq("user_id", user.id)
      .eq("occurred_at", row.occurred_at)
      .eq("trigger_cause", row.trigger_cause);
    if (lookupError) throw lookupError;
    const ids = (matches ?? []).map((r) => r.id);
    if (ids.length > 0) {
      const { error } = await supabase
        .from("sensitivity_history")
        .delete()
        .in("id", ids);
      if (error) throw error;
    }
  } catch {
    // Will be retried on next connectivity change
  }
}
