create table if not exists public.sensitivity_history (
  id            bigint generated by default as identity primary key,
  user_id       uuid not null references auth.users (id) on delete cascade,
  trigger_cause text not null,
  severity      text not null,
  notes         text,
  occurred_at   timestamptz not null default now(),
  created_at    timestamptz not null default now(),
  constraint sensitivity_history_severity_check
    check (severity in ('mild', 'moderate', 'severe'))
);

create index if not exists sensitivity_history_user_id_occurred_at_idx
  on public.sensitivity_history (user_id, occurred_at desc);

alter table public.sensitivity_history enable row level security;

create policy "Own sensitivity rows: select"
  on public.sensitivity_history
  for select using (auth.uid() = user_id);

create policy "Own sensitivity rows: insert"
  on public.sensitivity_history
  for insert with check (auth.uid() = user_id);

create policy "Own sensitivity rows: update"
  on public.sensitivity_history
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "Own sensitivity rows: delete"
  on public.sensitivity_history
  for delete using (auth.uid() = user_id);

notify pgrst, 'reload schema';
